name: Android CI & Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    # Grant permissions for actions to create GitHub Releases
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Gradle 8.1.1
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.1.1'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: Build debug APK
      run: ./gradlew assembleDebug

    # Optional: Still upload as artifact for easy access during/after run
    - name: Upload debug APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

    # Create a Draft GitHub Release and upload the APK (only on push to main)
    - name: Create Draft Release with Debug APK
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        # Creates a draft release. Remove draft: true to publish immediately.
        draft: true
        # Creates a pre-release. Remove prerelease: true for a full release.
        prerelease: true
        # Generate a tag name based on the commit SHA for uniqueness
        tag_name: debug-build-${{ github.sha }}
        name: Debug Build ${{ github.sha }}
        body: "Debug build generated by GitHub Actions workflow run ${{ github.run_id }}."
        files: |
          app/build/outputs/apk/debug/app-debug.apk

